### ISSUE TITLE
Delete repository

### ISSUE THREAD

**Issue by simnh** [znes/FlEnS#1]
I think we should remove this one for various reasons: 

* its does not follow any structure and is hard to maintain (many links do not work for example)
* there are better places to publish data than github.

I propose: 
* for scenario development we can use closed repositories that are deleted once completed
* the project leader (or person responsible drops the finanlized data at a plattform of choice, e.g. zenodo, osf, etc. 

If you agree, I would like you all to move your project specific stuff somewhere else (new repositories if still in development or publish on e.g. zenodo) 

We can also discuss this on the week in denmark, but I think we should really get rid of this one. Same holds for https://github.com/znes/cFlEnS.

**Comment by wolfbunke** [comment]
I don't agree. The scenarios for open_eGo in FlEnS are transparent stored and published on https://osf.io/rz7fq/ and https://osf.io/bpf36/ via github. If you talking about the closed "developing" Repro of cFlEnS it is something different because of duplications.  For the open_eGo project the FlEnS Repro is needed and there is no time for extra work. 

For further projects we could look what is needed, which data and transparency requirements should be meet and what are the advantages and disadvantages. But this repository should remain.

**Comment by simnh** [comment]
It's not if now, but if in the future. I actually think the way the scenarios are published is not transparent at all, as the project refers to the master, where now for example the socio economic examples exist. I just propose the following: 

* keep the scenarios that are still in development in a closed github repository (however, we should stick to a minimal structure there as well) 
* If the scenarios are finalized, publish these, and only these at zenodo. maybe together with the renpassGIS! code that works and the results from the model runs - this would be reproducible and max. transparent, I would not require much extra work, though I think its not really extra work but necessary work to keep the results reproducible. 

But we do not need to discuss this here, but can proceed at strategy week

**Comment by ckaldemeyer** [comment]
I think the general znes repository could be polished due to different projects/people (sometimes not even related to znes) that are using repos under the organisation..

**Comment by ckaldemeyer** [comment]
> I think the general znes repository could be polished due to different projects/people (sometimes not even related to znes) that are using repos under the organisation..

From outside it might look like a trashcan atm. :-)

**Comment by simnh** [comment]
> From outside it might look like a trashcan atm. :-)

at least we agree on this ;-)

**Comment by simnh** [comment]
Ok I just realized no one has real interest and actually its not my business. So I will close this one. 

Just as an info: The ANGUS scenarios will not be published in this directory...
