### ISSUE TITLE
Key error in 2050 scenario

### ISSUE THREAD

**Issue by MarlonSchlemminger** [znes/FlEnS#2]
I get a key error when I try to execute the renpass script with the 2050 scenario files. SQ and NEP scenarios are fine. Any idea why this happens and how to fix it?
![grafik](https://user-images.githubusercontent.com/22960010/38251681-6f510d46-3752-11e8-9bb7-df22fe794c03.png)

**Comment by eosram** [comment]
Do you use the dev-branch in renpass_gis and the ego-timeseries branch in FlEnS, this branch reflects the current up-to-date state of the eGo scenraios right @wolfbunke ?

**Comment by eosram** [comment]
Additionally as far as I know it we early on used to work with version 0.1.0 of oemof. I'm not sure, if there are any implications using v0.1.4 .

**Comment by MarlonSchlemminger** [comment]
Uh, I used the dev branch in FLEnS as well. Works with the ego_timeseries branch, thanks!
